<a href="https://colab.research.google.com/github/Allendecodes/Numpy_my_notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
array = np.array([1,2,3,4])

array = array * 2

print(array)

[2 4 6 8]


In [ ]:
array = np.array([['A','B','C'],['D','E','F']])

print(array.ndim)

2


Multidimensionl Indexing,shape

In [ ]:
array = np.array([[['A','B','C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
            [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q','R']],
             [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z',' ']]])

print(array.shape) #(3,3,3) (layer,rows,cols)
print(array.ndim) #No of Dimensions
print(array[1,1,1]) # Accesing elemnts

(3, 3, 3)
3
N


In [ ]:
array = np.array([[['A','B','C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
            [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q','R']],
             [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z',' ']]])

word = array[0,0,0] + array[1,2,0] + array[1,2,0] + array[2,0,2] # Multidimensional Indexing
print(word)

APPU


Indexing & Slicing

In [ ]:
array = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

print(array[::-1]) #negative indexing

print(array[1:4,1:4])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


Arithmetic

In [ ]:
array = np.array([1,2,3])


print(array + 1)
print(array - 1)
print(array * 3)
print(array / 4)
print(array ** 5)

[2 3 4]
[0 1 2]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
array = np.array([1,2,3])

print(np.sqrt(array)) # square root of numbers
print(np.round(array)) # rounded off of numbers

[1.         1.41421356 1.73205081]
[1 2 3]


In [ ]:
#Exercise
radii = np.array([1,2,3])

print(np.pi * radii ** 2) #Area of circle for different radius

[ 3.14159265 12.56637061 28.27433388]


In [ ]:
array1 = np. array ([1, 2, 3])
array2 = np. array ([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


Comparison operators

In [ ]:
scores = np.array([91, 55, 100, 73, 82, 64])

print(scores == 100)
print(scores >= 40)
scores[scores < 60] = 0
print(scores)


[False False  True False False False]
[ True  True  True  True  True  True]
[ 91   0 100  73  82  64]


Broadcasting

Broadcasting allows NumPy to perform operations on arrays
with different shapes by virtually expanding dimensions
so they match the larger array's shape.
The dimensions have the same size OR
One of the dimensions has a size of 1.

In [ ]:
array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2) # operands could not be broadcast together with shapes (2,4) (4,1),The dimensions have to be the same size OR One of the dimensions should have a size of 1.

(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [ ]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1 * array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Aggregate functions = summarize data and typically return a single value

In [ ]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(np.sum(array))
print(np.std(array))
print(np.mean(array))
print(np.var(array))
print(np.max(array))
print(np.min(array))
print(np.argmin(array)) #returns the position of the minimum number
print(np.argmax(array)) #returns the position of the maximum number
print(np.sum(array,axis = 0)) #sum of the columns
print(np.sum(array,axis = 1)) #sum of the rows

55
2.8722813232690143
5.5
8.25
10
1
0
9
[ 7  9 11 13 15]
[15 40]


Filtering

In [ ]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])
teenagers = ages[ages<18]
adults1 = ages[(ages>=18) & (ages<65)] #and operator
adults2 = ages[(ages>=18) | (ages<65)] #or  operator ,notice it returns the all numbers
seniors = ages[ages>=65]
evens = ages[ages % 2 == 0]
print(evens)
print(seniors)
print(adults1)
print(adults2)
print(teenagers)

[20 16 30 18 22 18 20]
[65 99]
[21 19 20 30 18 39 22 18 19 20 21]
[21 17 19 20 16 30 18 65 39 22 15 99 18 19 20 21]
[17 16 15]


In [ ]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

print(np.where(ages>18,ages,0))

[[21  0 19 20  0 30  0 65]
 [39 22  0 99  0 19 20 21]]


Random numbers

In [ ]:
rng = np.random.default_rng()

print(rng.integers(1,7))
#np.random.seed(seed = 1) #it prints the same output numbers if seed is set to 1
print(np.random.uniform(-1,1,3)) #Uniform allows equal chances of output numbers
print(rng.integers(1,7,(1,5)))

1
[ 0.93652315 -0.37315164  0.38464523]
[[1 3 2 3 4]]


In [ ]:
rng = np. random. default_rng()
array = np.array([1, 2, 3, 4, 5])
rng.shuffle(array)
print(array)

[3 5 4 2 1]


In [ ]:
rng = np.random.default_rng()
fruits = np.array(["apple", "orange", "banana", "coconut", "pineapple"])
fruit = rng.choice(fruits)
print(fruit)

orange
